<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

<h1 align="center"><font size="5">Final Project: Classification with Python</font></h1>


<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
    <li><a href="https://#Section_1">Instructions</a></li>
    <li><a href="https://#Section_2">About the Data</a></li>
    <li><a href="https://#Section_3">Importing Data </a></li>
    <li><a href="https://#Section_4">Data Preprocessing</a> </li>
    <li><a href="https://#Section_5">One Hot Encoding </a></li>
    <li><a href="https://#Section_6">Train and Test Data Split </a></li>
    <li><a href="https://#Section_7">Train Logistic Regression, KNN, Decision Tree, SVM, and Linear Regression models and return their appropriate accuracy scores</a></li>
</a></li>
</div>
<p>Estimated Time Needed: <strong>180 min</strong></p>
</div>

<hr>


# Instructions


In this notebook, you will  practice all the classification algorithms that we have learned in this course.


Below, is where we are going to use the classification algorithms to create a model based on our training data and evaluate our testing data using evaluation metrics learned in the course.

We will use some of the algorithms taught in the course, specifically:

1. Linear Regression
2. KNN
3. Decision Trees
4. Logistic Regression
5. SVM

We will evaluate our models using:

1.  Accuracy Score
2.  Jaccard Index
3.  F1-Score
4.  LogLoss
5.  Mean Absolute Error
6.  Mean Squared Error
7.  R2-Score

Finally, you will use your models to generate the report at the end. 


# About The Dataset


The original source of the data is Australian Government's Bureau of Meteorology and the latest data can be gathered from [http://www.bom.gov.au/climate/dwo/](http://www.bom.gov.au/climate/dwo/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01).

The dataset to be used has extra columns like 'RainToday' and our target is 'RainTomorrow', which was gathered from the Rattle at [https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData](https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)




This dataset contains observations of weather metrics for each day from 2008 to 2017. The **weatherAUS.csv** dataset includes the following fields:

| Field         | Description                                           | Unit            | Type   |
| ------------- | ----------------------------------------------------- | --------------- | ------ |
| Date          | Date of the Observation in YYYY-MM-DD                 | Date            | object |
| Location      | Location of the Observation                           | Location        | object |
| MinTemp       | Minimum temperature                                   | Celsius         | float  |
| MaxTemp       | Maximum temperature                                   | Celsius         | float  |
| Rainfall      | Amount of rainfall                                    | Millimeters     | float  |
| Evaporation   | Amount of evaporation                                 | Millimeters     | float  |
| Sunshine      | Amount of bright sunshine                             | hours           | float  |
| WindGustDir   | Direction of the strongest gust                       | Compass Points  | object |
| WindGustSpeed | Speed of the strongest gust                           | Kilometers/Hour | object |
| WindDir9am    | Wind direction averaged of 10 minutes prior to 9am    | Compass Points  | object |
| WindDir3pm    | Wind direction averaged of 10 minutes prior to 3pm    | Compass Points  | object |
| WindSpeed9am  | Wind speed averaged of 10 minutes prior to 9am        | Kilometers/Hour | float  |
| WindSpeed3pm  | Wind speed averaged of 10 minutes prior to 3pm        | Kilometers/Hour | float  |
| Humidity9am   | Humidity at 9am                                       | Percent         | float  |
| Humidity3pm   | Humidity at 3pm                                       | Percent         | float  |
| Pressure9am   | Atmospheric pressure reduced to mean sea level at 9am | Hectopascal     | float  |
| Pressure3pm   | Atmospheric pressure reduced to mean sea level at 3pm | Hectopascal     | float  |
| Cloud9am      | Fraction of the sky obscured by cloud at 9am          | Eights          | float  |
| Cloud3pm      | Fraction of the sky obscured by cloud at 3pm          | Eights          | float  |
| Temp9am       | Temperature at 9am                                    | Celsius         | float  |
| Temp3pm       | Temperature at 3pm                                    | Celsius         | float  |
| RainToday     | If there was rain today                               | Yes/No          | object |
| RainTomorrow  | If there is rain tomorrow                             | Yes/No          | float  |

Column definitions were gathered from [http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml](http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)



## **Import the required libraries**


In [1]:
# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented.
# !mamba install -qy pandas==1.3.4 numpy==1.21.4 seaborn==0.9.0 matplotlib==3.5.0 scikit-learn==0.20.1
# Note: If your environment doesn't support "!mamba install", use "!pip install"

In [2]:
# Surpress warnings:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [3]:
#you are running the lab in your  browser, so we will install the libraries using ``piplite``
import piplite
await piplite.install(['pandas'])
await piplite.install(['numpy'])

In [4]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

### Importing the Dataset


In [5]:
from pyodide.http import pyfetch

async def download(url, filename):
    response = await pyfetch(url)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())

In [6]:
path='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv'

In [7]:
await download(path, "Weather_Data.csv")
filename ="Weather_Data.csv"

In [8]:
df = pd.read_csv("Weather_Data.csv")
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

### Data Preprocessing


#### One Hot Encoding


First, we need to perform one hot encoding to convert categorical variables to binary variables.


In [9]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])

Next, we replace the values of the 'RainTomorrow' column changing them from a categorical column to a binary column. We do not use the `get_dummies` method because we would end up with two columns for 'RainTomorrow' and we do not want, since 'RainTomorrow' is our target.


In [10]:
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

### Training Data and Test Data


Now, we set our 'features' or x values and our Y or target variable.


In [11]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [12]:
df_sydney_processed = df_sydney_processed.astype(float)

In [13]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

### Linear Regression


#### Q1) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `10`.


In [14]:
#Enter Your Code, Execute and take the Screenshot
x_train, x_test, y_train, y_test = train_test_split(features, Y, test_size=0.2, random_state=10)
print('Train data set:', '\n')
print('Train X: ', '\n', '(rows, columns): ', x_train.shape)
print('Train Y: ', '\n', '(rows, columns): ', y_train.shape)
print('Test X: ', '\n', '(rows, columns): ', x_test.shape)
print('Test Y: ', '\n', '(rows, columns): ', y_test.shape)

Train data set: 

Train X:  
 (rows, columns):  (2616, 66)
Train Y:  
 (rows, columns):  (2616,)
Test X:  
 (rows, columns):  (655, 66)
Test Y:  
 (rows, columns):  (655,)


#### Q2) Create and train a Linear Regression model called LinearReg using the training data (`x_train`, `y_train`).


In [15]:
#Enter Your Code, Execute and take the Screenshot
LinearReg = LinearRegression()
LinearReg.fit(x_train, y_train)

LinearRegression()

In [16]:
# Added just to see the coefficients of this Multiple linear Regression
x_variables = np.asarray(x_train.columns)
Coeff = np.asarray(LinearReg.coef_)
LinearReg_Coeff = (dict(zip(x_variables, Coeff.T)))
print('Coefficients and Intercept of Multiple Linear Regression:')
print('Coefficients: ', LinearReg_Coeff)
print('Intercept: ', LinearReg.intercept_)

Coefficients and Intercept of Multiple Linear Regression:
Coefficients:  {'MinTemp': -0.023686250234865192, 'MaxTemp': 0.013006039978351428, 'Rainfall': 0.000729929096395473, 'Evaporation': 0.006493632537401358, 'Sunshine': -0.03516434936611677, 'WindGustSpeed': 0.00423733387974002, 'WindSpeed9am': 0.0018278833955902626, 'WindSpeed3pm': 0.0007900756241655916, 'Humidity9am': 0.0009567821463876865, 'Humidity3pm': 0.008559862096559463, 'Pressure9am': 0.007699922414079372, 'Pressure3pm': -0.009245898465177056, 'Cloud9am': -0.008880176447009308, 'Cloud3pm': 0.010048791022352656, 'Temp9am': 0.014467520580919775, 'Temp3pm': -0.003487031675056096, 'RainToday_No': 847590246.6599269, 'RainToday_Yes': 847590246.7679936, 'WindGustDir_E': -6413245258.435968, 'WindGustDir_ENE': -6413245258.565382, 'WindGustDir_ESE': -6413245258.419961, 'WindGustDir_N': -6413245258.558487, 'WindGustDir_NE': -6413245258.5458355, 'WindGustDir_NNE': -6413245258.568734, 'WindGustDir_NNW': -6413245258.56534, 'WindGustDir_

#### Q3) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [17]:
#Enter Your Code, Execute and take the Screenshot
predictions = LinearReg.predict(x_test)
predictions[0:10]

array([0.13187027, 0.27623177, 0.97818375, 0.28743553, 0.13241768,
       0.46044159, 0.35684204, 0.8563633 , 0.67498016, 0.03824997])

#### Q4) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [18]:
#Enter Your Code, Execute and take the Screenshot
LinearRegression_MAE = np.mean(np.absolute(predictions - y_test))
LinearRegression_MSE = np.mean((predictions - y_test) ** 2)
LinearRegression_R2 = metrics.r2_score(y_test, predictions)

print('Mean Absolute Error (MAE): %.4f' % LinearRegression_MAE)
print('Residual Sum of Squares (MSE): %.4f' % LinearRegression_MSE)
print('R2-Score: %.4f' % LinearRegression_R2)

Mean Absolute Error (MAE): 0.2563
Residual Sum of Squares (MSE): 0.1157
R2-Score: 0.4271


#### Q5) Show the MAE, MSE, and R2 in a tabular format using data frame for the linear model.


In [19]:
#Enter Your Code, Execute and take the Screenshot
LinearRegressionMetrics = pd.Series([LinearRegression_MAE, LinearRegression_MSE, LinearRegression_R2], 
                                   index=['Mean Absolute Error (MAE)', 'Residual Sum of Squares (MSE)', 'R2-Score'])
ReportColumns = ['Multiple Linear Regression']
Report = pd.DataFrame(LinearRegressionMetrics, columns=ReportColumns)
Report

Multiple Linear Regression
Mean Absolute Error (MAE)                        0.256319
Residual Sum of Squares (MSE)                    0.115720
R2-Score                                         0.427133

### KNN


#### Q6) Create and train a KNN model called KNN using the training data (`x_train`, `y_train`) with the `n_neighbors` parameter set to `4`.

**KNN without Normalizing the Data**

In [20]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output
KNN_NoStandard = KNeighborsClassifier(n_neighbors=4).fit(x_train, y_train)
KNN_NoStandard

KNeighborsClassifier(n_neighbors=4)

**KNN with Data Normalized**

In [21]:
# Normalize the Data, as mention in the Lab for K-Nearest Neighbours
features_normalize = preprocessing.StandardScaler().fit(features).transform(features.astype(float))
features_normalize[0:2]

array([[ 1.01512601, -0.13507807,  1.23613927,  0.37146005, -1.87896481,
        -0.04408087,  0.27304105,  0.09468284,  1.57493504,  1.80020165,
        -0.10463342,  0.19902353,  1.45711035,  1.58608764,  0.58822905,
        -0.1498131 , -1.6890139 ,  1.6890139 , -0.19683104, -0.26458131,
        -0.2114572 , -0.0962102 , -0.23341161, -0.21846239, -0.12709872,
        -0.14570551, -0.23341161, -0.14570551, -0.28075943, -0.22900939,
        -0.12459185,  1.13817336, -0.15731934, -0.20667842, -0.21224496,
        -0.15731934, -0.20667842, -0.1775832 , -0.1583367 , -0.16724183,
        -0.18031258, -0.16333775,  4.46855108, -0.1775832 , -0.19599158,
        -0.24484312, -0.1319786 , -0.79155161, -0.4172346 , -0.17481649,
        -0.48552917, -0.34946664, -0.33553693, -0.1319786 , -0.33327672,
        -0.13899878, -0.10841489, -0.13553087, -0.28454344, -0.26458131,
        -0.30236527,  4.5774469 , -0.11266543, -0.25587558, -0.24343717,
        -0.18742087],
       [ 1.01512601,  0.57871

In [22]:
x_train_Norm, x_test_Norm, y_train_Norm, y_test_Norm = train_test_split(features_normalize, Y, test_size=0.2, random_state=10)
print('Train data set:', '\n')
print('Train X Normalized: ', '\n', '(rows, columns): ', x_train_Norm.shape)
print('Train Y: ', '\n', '(rows, columns): ', y_train_Norm.shape)
print('Test X Normalized: ', '\n', '(rows, columns): ', x_test_Norm.shape)
print('Test Y: ', '\n', '(rows, columns): ', y_test_Norm.shape)

Train data set: 

Train X Normalized:  
 (rows, columns):  (2616, 66)
Train Y:  
 (rows, columns):  (2616,)
Test X Normalized:  
 (rows, columns):  (655, 66)
Test Y:  
 (rows, columns):  (655,)


In [23]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output
KNN_Standard = KNeighborsClassifier(n_neighbors=4).fit(x_train_Norm, y_train_Norm)
KNN_Standard

KNeighborsClassifier(n_neighbors=4)

#### Q7) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


**KNN without Normalizing the Data**

In [24]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output
predictions = KNN_NoStandard.predict(x_test)
predictions[0:10]

array([0., 0., 1., 0., 0., 0., 0., 1., 1., 0.])

In [25]:
y_test[0:10]

3066    0.0
2456    0.0
1629    1.0
838     1.0
2506    0.0
130     1.0
2404    1.0
1226    1.0
290     1.0
2136    0.0
Name: RainTomorrow, dtype: float64

**KNN with Data Normalized**

In [26]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output
predictions_Standard = KNN_Standard.predict(x_test_Norm)
predictions_Standard[0:10]

array([0., 1., 1., 1., 0., 0., 0., 1., 1., 0.])

In [27]:
y_test_Norm[0:10]

3066    0.0
2456    0.0
1629    1.0
838     1.0
2506    0.0
130     1.0
2404    1.0
1226    1.0
290     1.0
2136    0.0
Name: RainTomorrow, dtype: float64

#### Q8) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


**KNN without Normalizing the Data**

In [28]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output
# Accuracy Score
KNN_NonS_Accuracy_Score = accuracy_score(y_test, predictions)
# Jaccard Score
KNN_Nons_Jaccard_Index = jaccard_score(y_test, predictions)
# F1 Score
KNN_Nons_F1_Score = f1_score(y_test, predictions, average='weighted')

In [29]:
KNN_Nons_Score = pd.Series([KNN_NonS_Accuracy_Score, KNN_Nons_Jaccard_Index, KNN_Nons_F1_Score], 
                                   index=['Accuracy Score', 'Jaccard Index', 'F1-Score'])
KNN_NonS_Columns = ['KNN without Normalizing Data']
Report_KNN_Nons = pd.DataFrame(KNN_Nons_Score, columns=KNN_NonS_Columns)
Report_KNN_Nons

KNN without Normalizing Data
Accuracy Score                      0.818321
Jaccard Index                       0.425121
F1-Score                            0.802375

**KNN with Data Normalized**

In [30]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output
# Accuracy Score
KNN_Standard_Accuracy_Score = accuracy_score(y_test_Norm, predictions_Standard)
# Jaccard Score
KNN_Standard_Jaccard_Index = jaccard_score(y_test_Norm, predictions_Standard)
# F1 Score
KNN_Standard_F1_Score = f1_score(y_test_Norm, predictions_Standard, average='weighted')

In [31]:
KNN_Standard_Score = pd.Series([KNN_Standard_Accuracy_Score, KNN_Standard_Jaccard_Index, KNN_Standard_F1_Score], 
                                   index=['Accuracy Score', 'Jaccard Index', 'F1-Score'])
KNN_Standard_Columns = ['KNN with Data Normalized']
Report_KNN_Standard = pd.DataFrame(KNN_Standard_Score, columns=KNN_Standard_Columns)
Report_KNN_Standard

KNN with Data Normalized
Accuracy Score                  0.760305
Jaccard Index                   0.241546
F1-Score                        0.721176

In [32]:
Report_KNN = pd.concat([Report_KNN_Nons, Report_KNN_Standard], axis=1)
Report_KNN

KNN without Normalizing Data  KNN with Data Normalized
Accuracy Score                      0.818321                  0.760305
Jaccard Index                       0.425121                  0.241546
F1-Score                            0.802375                  0.721176

### Decision Tree


#### Q9) Create and train a Decision Tree model called Tree using the training data (`x_train`, `y_train`).


In [33]:
#Enter Your Code, Execute and take the Screenshot
Tree = DecisionTreeClassifier(criterion="entropy", max_depth = 6)
Tree

DecisionTreeClassifier(criterion='entropy', max_depth=6)

In [34]:
Tree.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=6)

#### Q10) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [35]:
#Enter Your Code, Execute and take the Screenshot
predictions = Tree.predict(x_test)
predictions[0:10]

array([0., 0., 1., 0., 0., 0., 0., 1., 1., 0.])

#### Q11) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [36]:
#Enter Your Code, Execute and take the Screenshot
# Accuracy Score
Tree_Accuracy_Score = accuracy_score(y_test, predictions)
# Jaccard Score
Tree_Jaccard_Index = jaccard_score(y_test, predictions)
# F1 Score
Tree_F1_Score = f1_score(y_test, predictions, average='weighted')

In [37]:
Tree_Score = pd.Series([Tree_Accuracy_Score, Tree_Jaccard_Index, Tree_F1_Score], 
                       index=['Accuracy Score', 'Jaccard Index', 'F1-Score'])
Tree_Columns = ['Decision Tree']
Report_Tree = pd.DataFrame(Tree_Score, columns=Tree_Columns)
Report_Tree

Decision Tree
Accuracy Score       0.827481
Jaccard Index        0.497778
F1-Score             0.822294

### Logistic Regression


#### Q12) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `1`.


In [38]:
#Enter Your Code, Execute and take the Screenshot
x_train, x_test, y_train, y_test = train_test_split(features, Y, test_size=0.2, random_state=1)
print('Train data set:', '\n')
print('Train X: ', '\n', '(rows, columns): ', x_train.shape)
print('Train Y: ', '\n', '(rows, columns): ', y_train.shape)
print('Test X: ', '\n', '(rows, columns): ', x_test.shape)
print('Test Y: ', '\n', '(rows, columns): ', y_test.shape)

Train data set: 

Train X:  
 (rows, columns):  (2616, 66)
Train Y:  
 (rows, columns):  (2616,)
Test X:  
 (rows, columns):  (655, 66)
Test Y:  
 (rows, columns):  (655,)


#### Q13) Create and train a LogisticRegression model called LR using the training data (`x_train`, `y_train`) with the `solver` parameter set to `liblinear`.


In [40]:
#Enter Your Code, Execute and take the Screenshot
LR = LogisticRegression(C=0.01, solver='liblinear')
LR.fit(x_train, y_train)

LogisticRegression(C=0.01, solver='liblinear')

#### Q14) Now, use the `predict` and `predict_proba` methods on the testing data (`x_test`) and save it as 2 arrays `predictions` and `predict_proba`.


In [41]:
#Enter Your Code, Execute and take the Screenshot
predictions = LR.predict(x_test)
predictions[0:10]

array([0., 0., 1., 0., 0., 1., 0., 0., 0., 0.])

In [42]:
predict_proba = LR.predict_proba(x_test)
predict_proba[0:10]

array([[0.71865892, 0.28134108],
       [0.97588314, 0.02411686],
       [0.49701327, 0.50298673],
       [0.66413145, 0.33586855],
       [0.97404733, 0.02595267],
       [0.04546303, 0.95453697],
       [0.6610167 , 0.3389833 ],
       [0.9569862 , 0.0430138 ],
       [0.84800124, 0.15199876],
       [0.95260729, 0.04739271]])

#### Q15) Using the `predictions`, `predict_proba` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [43]:
#Enter Your Code, Execute and take the Screenshot
# Accuracy Score
LR_Accuracy_Score = accuracy_score(y_test, predictions)
# Jaccard Score
LR_Jaccard_Index = jaccard_score(y_test, predictions)
# F1 Score
LR_F1_Score = f1_score(y_test, predictions, average='weighted')
# Log Loss
LR_Log_Loss = log_loss(y_test, predict_proba)

In [44]:
LogR_Score = pd.Series([LR_Accuracy_Score, LR_Jaccard_Index, LR_F1_Score, LR_Log_Loss], 
                       index=['Accuracy Score', 'Jaccard Index', 'F1-Score', 'Log Loss'])
LogR_Columns = ['Logistic Regression']
Report_LogR = pd.DataFrame(LogR_Score, columns=LogR_Columns)
Report_LogR

Logistic Regression
Accuracy Score             0.827481
Jaccard Index              0.484018
F1-Score                   0.820545
Log Loss                   0.380085

### SVM


#### Q16) Create and train a SVM model called SVM using the training data (`x_train`, `y_train`).


In [45]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output
SVM = svm.SVC(kernel='rbf')
SVM.fit(x_train, y_train)

SVC()

#### Q17) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [46]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output
predictions = SVM.predict(x_test)
predictions[0:10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
y_test[0:10]

255     0.0
1552    0.0
1353    0.0
1060    0.0
808     0.0
836     1.0
2108    0.0
3005    0.0
1401    0.0
602     0.0
Name: RainTomorrow, dtype: float64

#### Q18) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [48]:
#Enter Your Code, Execute and take the Screenshot
# Accuracy Score
SVM_Accuracy_Score = accuracy_score(y_test, predictions)
# Jaccard Score
SVM_Jaccard_Index = jaccard_score(y_test, predictions)
# F1 Score
SVM_F1_Score = f1_score(y_test, predictions, average='weighted')

In [49]:
SVM_Score = pd.Series([SVM_Accuracy_Score, SVM_Jaccard_Index, SVM_F1_Score], 
                       index=['Accuracy Score', 'Jaccard Index', 'F1-Score'])
SVM_Columns = ['Support Vector Machine']
Report_SVM = pd.DataFrame(SVM_Score, columns=SVM_Columns)
Report_SVM

Support Vector Machine
Accuracy Score                0.722137
Jaccard Index                 0.000000
F1-Score                      0.605622

### Report


#### Q19) Show the Accuracy,Jaccard Index,F1-Score and LogLoss in a tabular format using data frame for all of the above models.

\*LogLoss is only for Logistic Regression Model


In [50]:
ReportFinal = pd.concat([Report, Report_KNN, Report_Tree, Report_LogR, Report_SVM], axis=1)
ReportFinal.fillna('No value', inplace=True)
ReportFinal

Multiple Linear Regression  \
Mean Absolute Error (MAE)                       0.256319   
Residual Sum of Squares (MSE)                    0.11572   
R2-Score                                        0.427133   
Accuracy Score                                  No value   
Jaccard Index                                   No value   
F1-Score                                        No value   
Log Loss                                        No value   

                              KNN without Normalizing Data  \
Mean Absolute Error (MAE)                         No value   
Residual Sum of Squares (MSE)                     No value   
R2-Score                                          No value   
Accuracy Score                                    0.818321   
Jaccard Index                                     0.425121   
F1-Score                                          0.802375   
Log Loss                                          No value   

                              KNN with Data Normalized Decision Tree  \
Mean Absolute Error (MAE)                     No value      No value   
Residual Sum of Squares (MSE)                 No value      No value   
R2-Score                                      No value      No value   
Accuracy Score                                0.760305      0.827481   
Jaccard Index                                 0.241546      0.497778   
F1-Score                                      0.721176      0.822294   
Log Loss                                      No value      No value   

                              Logistic Regression Support Vector Machine  
Mean Absolute Error (MAE)                No value               No value  
Residual Sum of Squares (MSE)            No value               No value  
R2-Score                                 No value               No value  
Accuracy Score                           0.827481               0.722137  
Jaccard Index                            0.484018                    0.0  
F1-Score                                 0.820545               0.605622  
Log Loss                                 0.380085               No value

<h2 id="Section_5">  How to submit </h2>

<p>Once you complete your notebook you will have to share it. You can download the notebook by navigating to "File" and clicking on "Download" button.

<p>This will save the (.ipynb) file on your computer. Once saved, you can upload this file in the "My Submission" tab, of the "Peer-graded Assignment" section.  


<h2>About the Authors:</h2> 

<a href="https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01">Joseph Santarcangelo</a> has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

### Other Contributors

[Svitlana Kramar](https://www.linkedin.com/in/svitlana-kramar/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork30654641-2022-01-01)


## Change Log

| Date (YYYY-MM-DD) | Version | Changed By    | Change Description          |
| ----------------- | ------- | ------------- | --------------------------- |
| 2023-04-10        | 2.1     | Anita Verma  | Removed "RISK_MM" and updated Q14 and Q15 |
| 2022-06-22        | 2.0     | Svitlana K.   | Deleted GridSearch and Mock |


## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
